name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} << 'EOF'
          if [ ! -d "/home/ubuntu/deploy/mahjongbot" ]; then
            mkdir -p /home/ubuntu/deploy
            cd /home/ubuntu/deploy
            git clone git@github.com:your-repo/mahjongbot.git
          else
            cd /home/ubuntu/deploy/mahjongbot
            git pull origin main
          fi
          cd /home/ubuntu/deploy/mahjongbot
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          docker-compose down
          docker-compose up -d --build
        EOF
